language: objective-c

osx_image: xcode8

notifications:
  slack: rxswift:3ykt2Z61f8GkdvhCZTYPduOL
  email: false

install: true

script: 
  - mkdir build && . ./scripts/common.sh && true #rx "Tests" Release "${DEFAULT_IOS_SIMULATOR}" build

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725
